version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cefmp4_processor_app
    restart: unless-stopped
    volumes:
      - ./local_watch_dir:/app/local_watch_dir # Mount the local watch directory
      # - ./src:/app/src # For development: live code reload (requires watchdog or similar in app)
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - APP_ENV=${APP_ENV:-production} # Default to production in Docker
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL:-http://minio:9000}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID:-MINIO_ACCESS_KEY}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY:-MINIO_SECRET_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME:-video-streams}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - STREAM_TIMEOUT_SECONDS=${STREAM_TIMEOUT_SECONDS:-30}
      - CHUNK_SIZE_BYTES=${CHUNK_SIZE_BYTES:-10485760} # 10MB
      - FFPROBE_PATH=${FFPROBE_PATH}
      - PROM_PORT=${PROM_PORT:-8000} # Added PROM_PORT env var
    ports:
      - "${PROM_PORT:-8000}:${PROM_PORT:-8000}" # Expose PROM_PORT
    depends_on:
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - cefmp4_network

  minio:
    image: minio/minio:RELEASE.2023-09-07T02-05-02Z
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # MinIO Console
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY_ID:-minioadmin}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_ACCESS_KEY:-minioadmin}
    command: server /data --console-address ":9001"

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    # ports: # Uncomment to expose Redis for direct debugging
    #   - "6379:6379"

volumes:
  minio-data:
  redis-data:
